name: Feature branch integration and deployment

env:
  NODE_VERSION: 20

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-javascript:
    name: Run JS linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm i --force

      - name: Lint
        run: npm lint
