name: Deploy to production

env:
  NODE_VERSION: 20

on:
  push:
    branches:
      - main

jobs:
  # Deploy
  # https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm i -g vercel@latest

        # https://vercel.com/docs/cli/pull#yes
      - name: Pull vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

        # https://vercel.com/docs/cli/build
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
